config/routes.rb
Tranquility::Application.routes.draw do
  
  get "landing/index"

  resources :categories
  resources :usereffects
  resources :accountactions
  resources :customers
  resources :accounts

  root :to => 'landing#index'

end

app/controllers/accountactions_controller.rb
class AccountactionsController < ApplicationController
  # GET /accountactions
  # GET /accountactions.xml
  def index
    @accountactions = Accountaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accountactions }
    end
  end

  # GET /accountactions/1
  # GET /accountactions/1.xml
  def show
    @accountaction = Accountaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @accountaction }
    end
  end

  # GET /accountactions/new
  # GET /accountactions/new.xml
  def new
    @accountaction = Accountaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @accountaction }
    end

  end

  # GET /accountactions/1/edit
  def edit
    @accountaction = Accountaction.find(params[:id])
  end

  # POST /accountactions
  # POST /accountactions.xml
  def create
    @accountaction = Accountaction.new(params[:accountaction])

    respond_to do |format|
      if @accountaction.save
        format.html { redirect_to( account_path(current_account_id), :notice => 'Accountaction was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /accountactions/1
  # PUT /accountactions/1.xml
  def update
    @accountaction = Accountaction.find(params[:id])

    respond_to do |format|
      if @accountaction.update_attributes(params[:accountaction])
        format.html { redirect_to(@accountaction, :notice => 'Accountaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @accountaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accountactions/1
  # DELETE /accountactions/1.xml
  def destroy
    @accountaction = Accountaction.find(params[:id])
    @accountaction.destroy

    respond_to do |format|
      format.html { redirect_to(accountactions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accountactions_helper.rb
module AccountactionsHelper
end

app/views/accountactions/_form.haml
= form_for(@accountaction) do |f|
  - if @accountaction.errors.any?
    #error_explanation
      %h2
        = pluralize(@accountaction.errors.count, "error")
        prohibited this accountaction from being saved:
      %ul
        - @accountaction.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :category_id
    %br/
    = f.collection_select :category_id, Account.find(current_account_id).categories, :id, :name, :prompt => 'Select Category'
  .field
    = f.hidden_field :account_id, :value => current_account_id
  .actions
    = f.submit

app/views/accountactions/edit.haml
%h1 Editing accountaction
= render 'form'
= link_to 'Show', @accountaction
|
\#{link_to 'Back', accountactions_path}

app/views/accountactions/index.haml
%h1 Listing accountactions
%table
  %tr
    %th Description
    %th Category
    %th
    %th
    %th
  - @accountactions.each do |accountaction|
    %tr
      %td= accountaction.description
      %td= accountaction.category_id
      %td= link_to 'Show', accountaction
      %td= link_to 'Edit', edit_accountaction_path(accountaction)
      %td= link_to 'Destroy', accountaction, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Accountaction', new_accountaction_path

app/views/accountactions/new.haml
%h1 New accountaction
= render 'form'
= link_to 'Back', accountactions_path

app/views/accountactions/show.haml
%p#notice= notice
%p
  %b Description:
  = @accountaction.description
%p
  %b Category:
  = @accountaction.category_id
= link_to 'Edit', edit_accountaction_path(@accountaction)
|
\#{link_to 'Back', accountactions_path}