config/routes.rb
Tranquility::Application.routes.draw do
  
  get "landing/index"

  resources :categories
  resources :usereffects
  resources :accountactions
  resources :customers
  resources :accounts

  root :to => 'landing#index'

end

app/models/usereffect.rb
class Usereffect < ActiveRecord::Base
  belongs_to :accountaction
end

app/controllers/usereffects_controller.rb
class UsereffectsController < ApplicationController
  # GET /usereffects
  # GET /usereffects.xml
  def index
    @usereffects = Usereffect.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @usereffects }
    end
  end

  # GET /usereffects/1
  # GET /usereffects/1.xml
  def show
    @usereffect = Usereffect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @usereffect }
    end
  end

  # GET /usereffects/new
  # GET /usereffects/new.xml
  def new
    @usereffect = Usereffect.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @usereffect }
    end
  end

  # GET /usereffects/1/edit
  def edit
    @usereffect = Usereffect.find(params[:id])
  end

  # POST /usereffects
  # POST /usereffects.xml
  def create
    @usereffect = Usereffect.new(params[:usereffect])

    respond_to do |format|
      if @usereffect.save
        format.html { redirect_to(@usereffect, :notice => 'Usereffect was successfully created.') }
        format.xml  { render :xml => @usereffect, :status => :created, :location => @usereffect }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @usereffect.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /usereffects/1
  # PUT /usereffects/1.xml
  def update
    @usereffect = Usereffect.find(params[:id])

    respond_to do |format|
      if @usereffect.update_attributes(params[:usereffect])
        format.html { redirect_to(@usereffect, :notice => 'Usereffect was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @usereffect.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /usereffects/1
  # DELETE /usereffects/1.xml
  def destroy
    @usereffect = Usereffect.find(params[:id])
    @usereffect.destroy

    respond_to do |format|
      format.html { redirect_to(usereffects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/usereffects_helper.rb
module UsereffectsHelper
end

app/views/usereffects/_form.haml
= form_for(@usereffect) do |f|
  - if @usereffect.errors.any?
    #error_explanation
      %h2
        = pluralize(@usereffect.errors.count, "error")
        prohibited this usereffect from being saved:
      %ul
        - @usereffect.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :user_id
    %br/
    = f.text_field :user_id
  .field
    = f.label :action_id
    %br/
    = f.text_field :action_id
  .actions
    = f.submit

app/views/usereffects/edit.haml
%h1 Editing usereffect
= render 'form'
= link_to 'Show', @usereffect
|
\#{link_to 'Back', usereffects_path}

app/views/usereffects/index.haml
%h1 Listing usereffects
%table
  %tr
    %th User
    %th Action
    %th
    %th
    %th
  - @usereffects.each do |usereffect|
    %tr
      %td= usereffect.user_id
      %td= usereffect.action_id
      %td= link_to 'Show', usereffect
      %td= link_to 'Edit', edit_usereffect_path(usereffect)
      %td= link_to 'Destroy', usereffect, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Usereffect', new_usereffect_path

app/views/usereffects/new.haml
%h1 New usereffect
= render 'form'
= link_to 'Back', usereffects_path

app/views/usereffects/show.haml
%p#notice= notice
%p
  %b User:
  = @usereffect.user_id
%p
  %b Action:
  = @usereffect.action_id
= link_to 'Edit', edit_usereffect_path(@usereffect)
|
\#{link_to 'Back', usereffects_path}