config/routes.rb
Tranquility::Application.routes.draw do
  
  get "landing/index"

  resources :categories
  resources :usereffects
  resources :accountactions
  resources :customers
  resources :accounts

  root :to => 'landing#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :customers
  has_many :categories
  has_many :accountactions
end

app/models/accountaction.rb
class Accountaction < ActiveRecord::Base
  has_many :usereffects
  belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.xml
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.xml
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.xml
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.xml
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => 'Account was successfully created.') }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Account was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.xml
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(accounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.haml
= form_for(@account) do |f|
  - if @account.errors.any?
    #error_explanation
      %h2
        = pluralize(@account.errors.count, "error")
        prohibited this account from being saved:
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :website
    %br/
    = f.text_field :website
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .actions
    = f.submit

app/views/accounts/edit.haml
%h1 Editing account
= render 'form'
= link_to 'Show', @account
|
\#{link_to 'Back', accounts_path}

app/views/accounts/index.haml
%h1 Listing accounts
%table
  %tr
    %th Name
    %th Website
    %th Email
    %th
    %th
    %th
  - @accounts.each do |account|
    %tr
      %td= account.name
      %td= account.website
      %td= account.email
      %td= link_to 'Show', account
      %td= link_to 'Edit', edit_account_path(account)
      %td= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Account', new_account_path

app/views/accounts/new.haml
%h1 New account
= render 'form'
= link_to 'Back', accounts_path

app/views/accounts/show.haml
%p#notice= notice
%p
  %b Name:
  = @account.name
%p
  %b Website:
  = @account.website
%p
  %b Email:
  = @account.email

%br
%h2 Recent History
%hr
- @account.accountactions.each do |action|
  %p 
    = action.created_at
    |
    = action.description.split(' ').first(15).join(' ')
    |
    = link_to 'Edit', edit_accountaction_path(action)
    |
    = link_to 'Delete', accountaction_path(action), :method => :delete
  %hr	

= link_to 'New Action', new_accountaction_path